#!/bin/bash
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=12:mem=7800mb

cd $PBS_O_WORKDIR

module load intel-suite/2015.1
module load papi/5.3.0
module load scalasca/2.2.intel

# Calculations

./run
